import type { UIProduct, UIOrder } from "./types";

export const PRODUCTS: UIProduct[] = [
  { id: "P001", name: "Aashirvaad Atta (10kg)", category: "Staples", categoryId: "cat1", price: 340, unit: "bag", stock: 42, stockUnit: "bags", status: "In Stock", emoji: "🌾" },
  { id: "P002", name: "Tata Salt (1kg)", category: "Essentials", categoryId: "cat2", price: 22, unit: "pack", stock: 4, stockUnit: "packs", status: "Low Stock", emoji: "🧂" },
  { id: "P003", name: "Sunflower Oil (1L)", category: "Oils", categoryId: "cat3", price: 135, unit: "bottle", stock: 5, stockUnit: "bottles", status: "Low Stock", emoji: "🫙" },
  { id: "P004", name: "Toor Dal (1kg)", category: "Pulses", categoryId: "cat4", price: 148, unit: "kg", stock: 28, stockUnit: "kg", status: "In Stock", emoji: "🫘" },
  { id: "P005", name: "Amul Butter (500g)", category: "Dairy", categoryId: "cat5", price: 260, unit: "pack", stock: 7, stockUnit: "packs", status: "Low Stock", emoji: "🧈" },
  { id: "P006", name: "Basmati Rice (5kg)", category: "Staples", categoryId: "cat1", price: 420, unit: "bag", stock: 0, stockUnit: "bags", status: "Out of Stock", emoji: "🍚" },
  { id: "P007", name: "Red Chilli Powder (200g)", category: "Spices", categoryId: "cat6", price: 62, unit: "pack", stock: 31, stockUnit: "packs", status: "In Stock", emoji: "🌶️" },
  { id: "P008", name: "Moong Dal (500g)", category: "Pulses", categoryId: "cat4", price: 74, unit: "pack", stock: 19, stockUnit: "packs", status: "In Stock", emoji: "🫘" },
  { id: "P009", name: "Parle-G Biscuit (800g)", category: "Snacks", categoryId: "cat7", price: 50, unit: "pack", stock: 3, stockUnit: "packs", status: "Low Stock", emoji: "🍪" },
  { id: "P010", name: "Amul Full Cream Milk (1L)", category: "Dairy", categoryId: "cat5", price: 66, unit: "packet", stock: 24, stockUnit: "packets", status: "In Stock", emoji: "🥛" },
  { id: "P011", name: "Colgate Toothpaste (200g)", category: "Personal Care", categoryId: "cat8", price: 115, unit: "tube", stock: 18, stockUnit: "tubes", status: "In Stock", emoji: "🪥" },
  { id: "P012", name: "Dettol Soap (125g)", category: "Personal Care", categoryId: "cat8", price: 60, unit: "bar", stock: 6, stockUnit: "bars", status: "Low Stock", emoji: "🧼" },
];

export const ORDERS: UIOrder[] = [
  {
    id: "order1",
    orderNumber: "#SB-1082",
    customer: "Priya Sharma",
    phone: "98765 43210",
    items: [
      { name: "Aashirvaad Atta (10kg)", qty: 1, price: 340 },
      { name: "Toor Dal (1kg)", qty: 2, price: 296 },
      { name: "Sunflower Oil (1L)", qty: 2, price: 270 },
      { name: "Tata Salt (1kg)", qty: 2, price: 44 },
      { name: "Amul Full Cream Milk (1L)", qty: 4, price: 264 },
    ],
    orderTime: "09:15 AM",
    pickupTime: "11:30 AM",
    status: "Ready for Pickup",
  },
  {
    id: "order2",
    orderNumber: "#SB-1081",
    customer: "Rajesh Kumar",
    phone: "87654 32109",
    items: [
      { name: "Basmati Rice (5kg)", qty: 1, price: 420 },
      { name: "Red Chilli Powder (200g)", qty: 2, price: 124 },
      { name: "Moong Dal (500g)", qty: 1, price: 74 },
    ],
    orderTime: "09:42 AM",
    pickupTime: "11:00 AM",
    status: "Preparing",
  },
  {
    id: "order3",
    orderNumber: "#SB-1080",
    customer: "Ananya Patel",
    phone: "76543 21098",
    items: [
      { name: "Aashirvaad Atta (10kg)", qty: 2, price: 680 },
      { name: "Toor Dal (1kg)", qty: 5, price: 740 },
      { name: "Sunflower Oil (1L)", qty: 3, price: 405 },
      { name: "Amul Butter (500g)", qty: 1, price: 260 },
      { name: "Tata Salt (1kg)", qty: 2, price: 44 },
      { name: "Amul Full Cream Milk (1L)", qty: 6, price: 396 },
    ],
    orderTime: "08:55 AM",
    pickupTime: "10:30 AM",
    status: "Picked Up",
  },
  {
    id: "order4",
    orderNumber: "#SB-1079",
    customer: "Suresh Nair",
    phone: "65432 10987",
    items: [
      { name: "Red Chilli Powder (200g)", qty: 1, price: 62 },
      { name: "Moong Dal (500g)", qty: 2, price: 148 },
    ],
    orderTime: "10:02 AM",
    pickupTime: "12:00 PM",
    status: "Pending",
  },
  {
    id: "order5",
    orderNumber: "#SB-1078",
    customer: "Deepa Menon",
    phone: "54321 09876",
    items: [
      { name: "Aashirvaad Atta (10kg)", qty: 1, price: 340 },
      { name: "Sunflower Oil (1L)", qty: 2, price: 270 },
      { name: "Toor Dal (1kg)", qty: 1, price: 148 },
      { name: "Tata Salt (1kg)", qty: 2, price: 44 },
      { name: "Parle-G Biscuit (800g)", qty: 1, price: 50 },
    ],
    orderTime: "10:28 AM",
    pickupTime: "01:00 PM",
    status: "Pending",
  },
  {
    id: "order6",
    orderNumber: "#SB-1077",
    customer: "Karthik Iyer",
    phone: "43210 98765",
    items: [
      { name: "Basmati Rice (5kg)", qty: 2, price: 840 },
      { name: "Amul Full Cream Milk (1L)", qty: 6, price: 396 },
    ],
    orderTime: "08:10 AM",
    pickupTime: "09:30 AM",
    status: "Picked Up",
  },
  {
    id: "order7",
    orderNumber: "#SB-1076",
    customer: "Meena Krishnan",
    phone: "32109 87654",
    items: [
      { name: "Toor Dal (1kg)", qty: 3, price: 444 },
      { name: "Red Chilli Powder (200g)", qty: 2, price: 124 },
      { name: "Amul Butter (500g)", qty: 2, price: 520 },
    ],
    orderTime: "07:45 AM",
    pickupTime: "09:00 AM",
    status: "Picked Up",
  },
];

export const WEEKLY_SALES = [
  { day: "Mon", revenue: 8240, orders: 14 },
  { day: "Tue", revenue: 11580, orders: 19 },
  { day: "Wed", revenue: 9720, orders: 16 },
  { day: "Thu", revenue: 14350, orders: 23 },
  { day: "Fri", revenue: 16900, orders: 28 },
  { day: "Sat", revenue: 19450, orders: 32 },
  { day: "Sun", revenue: 12450, orders: 24 },
];
